### ISSUE TITLE
Dependency on Version 3.5.0 prevents generate class files

### ISSUE THREAD

**Issue by briantq** [Wolfgang-Schuetzelhofer/jcypher#28]
I have been trying to debug an issue where my project stopped generating class files, even though the build never failed.  I tracked it down to simply adding a dependency on jcypher.  Eventually I tried to compile the same app on the master branch to see if it had issues.  I found it compiled just fine, but was pointed to the 3.4.0 version.  I found 3.4.1 compile just fine.  When I changed the version to 3.5.0, no class files were generated for the iot package under target/classes. 

I think the work you did on this project is quite impressive and would love to try it out.  Unfortunately, the latest version appears to break in maven.  

If you think it's an environment issue, I am happy to share any information you might think would be helpful.

**Comment by Wolfgang-Schuetzelhofer** [comment]
JCypher 3.5.0 compiles for Java 1.8, so maybe that's the problem in your case.
But in general if you add a dependency to JCypher, the JCypher jar file is simply down-loaded from maven central and included in your classpath.
If you want to compile JCypher for Java 1.7, you need to clone the project, change the pom.xml to compile for Java 1.7. In this case however you will get some errors because the code is not completely backwards-compatible to Java 1.7, but it requires only 2 or 3 minor fixes in the code (JCypher 3.6.0 will be backwards-compatible with Java 1.7).

I hope this info helps. Let me know if I can be of more help.

Best regards,
Wolfgang

**Comment by mpetris** [comment]
Current HEAD of the master branch should compile with 1.7 since Wolfgang
merged my pull request three days ago. One of my changes was to make it
compile with 1.7. If you want to give it a try. Just make sure the
pom.xml is set to 1.7.
Best,
Marco

Am 17.10.2016 um 16:22 schrieb Wolfgang Schuetzelhofer:

**Comment by briantq** [comment]
That was indeed it.  When I changed the compilation version to 1.8 it started to work.  Thank you very much!
